# PLOT SCRIPT CONFIGURATION
# where to save a copy of the config used
config_copy_path: "/data/PINCAST/manuscript_1/verification/lcnn/{id}/{id}_config.yaml"

### INPUT CONFIG ###
metric_exp_ids: ["lcnn-logcosh-21082022"]
# the path to the CSV file recording which metrics have been calculated, bad timestamps
done_csv_path: "/data/PINCAST/manuscript_1/verification/lcnn/{id}/done_predict_{id}.csv"
# template path to the npy files recording the values of metrics that have been calculated
metrics_npy_path: "/data/PINCAST/manuscript_1/verification/lcnn/{id}/{method}/{id}_{metric}_{method}.npy"
# path to the text file containing metric names in order
name_path: "/data/PINCAST/manuscript_1/verification/lcnn/{id}/{method}/{id}_{metric}_{method}_names.txt"
# which metrics to plot? "CAT", "CONT", "FSS", "RAPSD", "INTENSITY_SCALE"
metrics: ["CAT", "FSS"] #, "INTENSITY_SCALE"]
# metrics: ["CONT"]

methods:
  # lcnn-logcosh-30lt-17062022:
  #   label: "L-CNN logcosh"
  #   color: "#1b9e77"
  #   linestyle: "solid"
  # # lcnn-logcosh-1x1-30lt:
  # #   label: "L-CNN logcosh 1x1"
  # #   color: "#1b9e77"
  # #   linestyle: "dotted"
  # # # LCNN MS-SSIM
  # # lcnn-msssim-30lt-20062022:
  # #   label: "L-CNN MS-SSIM"
  # #   color: "#1b9e77"
  # #   linestyle: "solid"
  # lcnn-diff-logcosh-30lt-20062022:
  #   label: "L-CNN-D logcosh"
  #   color: "#d95f02"
  #   linestyle: "solid"
  lcnn-diff-rmse-30lt-20062022:
    label: "L-CNN"
    color: "#02B8CE"
    linestyle: "solid"
  # lcnn-diff-mssim-30lt:
  #   label: "L-CNN-D MS-SSIM 1000"
  #   color: "#d95f02"
  #   linestyle: "dashdot"
  # lcnn-diff-mssim-30lt-20062022:
  #   label: "L-CNN-D MS-SSIM"
  #   color: "#d95f02"
  #   linestyle: "dotted"
  # lcnn-diff-ssim-30lt-20062022:
  #   label: "L-CNN-D SSIM"
  #   color: "#d95f02"
  #   linestyle: "dashdot"
  t11-rn-logcosh-lt30:
    label: "RainNet"
    color: "#303193"
    linestyle: "dashed"
  # t13-rn-msssim-lt30:
  #   label: "RainNet MS-SSIM"
  #   color: "#7570b3"
  #   linestyle: "solid"
  linda:
    label: "LINDA"
    color: "#000"
    linestyle: "dashdot"
  extrapolation:
    label: "Advection"
    color: "#3A66E3"
    linestyle: "dotted"

### OUTPUT CONFIG ###
exp_id: "lcnn-logcosh-21082022-figs-erad"
# path template for where to save figures
path_save: "/data/PINCAST/manuscript_1/verification/lcnn/{id}/{method}/{method}_{metric}.png"

### PLOT CONFIG ###
# leadtimes for which the metrics were calculated as units of timestep minutes
timestep: 5
leadtimes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
stylefile: presentation.mplstyle

# 13,
# 14,
# 15,
# 16,
# 17,
# 18,
# 19,
# 20,
# 21,
# 22,
# 23,
# 24,
# 25,
# 26,
# 27,
# 28,
# 29,
# 30,
# 31,
# 32,
# 33,
# 34,
# 35,
# 36,
# data quality plot config
dq_plot:
  # rotation of bar labels in deg
  label_rot: 40

# continuous metric plot config
cont_plot:
  # no hard-coded ylim
  # MAE
  ylim_val: [0.074, 0.251]
  yticks: [-1, 1, 0.025]
  # ME
  # ylim_val: [-0.12, 0.001]
  # yticks: [-1, 1, 0.01]
  xlim_val: [5, 60]
  xticks: [5, 61, 5]
  plot_epx_id: false

# categorical metric plot config
cat_plot:
  xlim_val: [5, 60]
  xticks: [5, 61, 5]
  plot_epx_id: false

# fss metric plot config
fss_plot:
  xlim_val: [5, 60]
  xticks: [5, 61, 5]
  plot_epx_id: false

# RAPSD metric plot config
rapsd_plot:
  subplot_kwargs: {}
  lts: [1, 3, 6, 12, 18, 24, 30, 36]
  n_scales: 256

# intensity scale metric plot config
intensity_scale_plot:
  subplot_kwargs: {}
  thresh: [0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0]
  scales: [1.0, 2.0, 4.0, 8.0, 16.0]
  kmperpixel: 1.0
  vminmax: [0, 1]

# SSIM plot parameters
ssim_plot:
  xlim_val: [5, 60]
  xticks: [5, 61, 5]
  plot_epx_id: false
  ylim_val: [0.5, 1.0]
  yticks: [0.5, 1.01, 0.05]
